/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.joedoe;
import java.util.List;
import java.util.ArrayList;
import java.util.logging.Logger;

public class DiamondPrinter {
    private Logger log = Logger.getLogger(DiamondPrinter.class.getName());

    public List<String> printToList(char a) {
        List<String> ans = new ArrayList<String>();
        String alpha = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
        int count = alpha.indexOf(a)+1;
        for(int i = 0; i < count; i++) {
            String extralr = "";
            for(int j = 0; j < count-i-1; j++) {
                extralr += ' ';
            }
            String extramid = "";
            for(int j = 0; j < i*2-1; j++) {
                extramid += ' ';
            }
            if(i==0) {
                ans.add(extralr+"A"+extralr);
            }
            else {
                ans.add(extralr+alpha.charAt(i)+extramid+alpha.charAt(i)+extralr);
            }
        }
        for(int i = count-2; i>=0; i--) {
            ans.add(ans.get(i));
        }
        return ans;
    }
}
