/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.joedoe;

import java.util.ArrayList;
import java.util.List;
import java.util.logging.Logger;

class DiamondPrinter {
    private List<String> diamond = new ArrayList<>();
    private int c, size, middle;
    private final static int A = 65;
    private Logger logger = Logger.getLogger(DiamondPrinter.class.getName());

    public List<String> printToList(char c) {
        this.c = c;
        size = (this.c - A) * 2 + 1;
        middle = size / 2;
        logger.info("Char: " + this.c +  " Size: " + size + " Middle: " + middle);
        for (int i = 0; i < size; i++) {
            diamond.add(createRow(i));
        }
        return diamond;
    }

    private String createRow(int index) {
        StringBuilder sb = getStringBuilderFilledWithSpaces();
        String letter;
        int pos1, pos2;
        if (index <= middle) {
            letter = Character.toString((char) (A + index));
            pos1 = middle - index;
            pos2 = middle + index;
        } else {
            letter = Character.toString((char) (c - index + middle));
            pos1 = middle - (size - 1 - index);
            pos2 = middle + (size - 1 - index);
        }
        logger.info("Letter: " + letter + " Pos1/2: " + pos1 + "/" + pos2);
        sb.replace(pos1, pos1 + 1, letter);
        sb.replace(pos2, pos2 + 1, letter);
        return sb.toString();
    }

    private StringBuilder getStringBuilderFilledWithSpaces() {
        StringBuilder sb = new StringBuilder();
        while (sb.length() < size) {
            sb.append(" ");
        }
        return sb;
    }
}
